credenciais:
  admin:
    nome: "Administrador"
    email: "admin@condominio.com"
    senha_hash: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"  # admin
  sindico:
    nome: "Síndico"
    email: "sindico@condominio.com"
    senha_hash: "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"  # sindico

configuracoes:
  cookie:
    nome: "condominio_auth"
    chave: "chave_secreta_do_condominio"
    expiracao_dias: 30